In [178]:
import os
import pandas as pd
import re
from bisect import bisect_right

# ----------------------------
# SETTINGS
# ----------------------------
WIKI_TREATIES = "./wiki-treaties_formatted.csv"
UNO_TREATIES = "./UNO-Treaties.csv"
INSTRUMENTS = "../instruments/ohchr_instruments_detailed.csv"
CONV_PROT_REC = "../conv-prot-rec/conventions-protocols-recommendations.csv"
RESOLUTIONS_TRIM = "../resolutions/ga_resolutions_1946_2019_3100-trim.csv"

df_wiki = pd.read_csv(WIKI_TREATIES)
df_uno = pd.read_csv(UNO_TREATIES)
df_ins = pd.read_csv(INSTRUMENTS)
df_conv = pd.read_csv(CONV_PROT_REC)
df_res = pd.read_csv(RESOLUTIONS_TRIM)

df_res = df_res.head(100)

df_wiki.head()

,year,name,url,note,summary,cleaned_note,cleaned_title
0,1900,Treaty of Paris,https://en.wikipedia.org/wiki/Treaty_of_Paris_...,NaN,Ends all conflicting claims over Río Muni ( Eq...,NaN,Treaty of Paris
1,1900,Treaty of Washington,https://en.wikipedia.org/wiki/Treaty_of_Washin...,NaN,Seeks to remove any ground of misunderstanding...,NaN,Treaty of Washington
2,1900,Convention for the Preservation of Wild Animal...,https://en.wikipedia.org/wiki/Convention_for_t...,NaN,First international agreement on wildlife cons...,NaN,Convention for the Preservation of Wild Animal...
3,1901,Hay–Pauncefote Treaty,https://en.wikipedia.org/wiki/Hay%E2%80%93Paun...,NaN,Replaces the Clayton–Bulwer Treaty,NaN,Hay–Pauncefote Treaty
4,1901,Boxer Protocol,https://en.wikipedia.org/wiki/Boxer_Protocol,Also known as the Peace Agreement between the ...,Peace agreement between the Eight-Nation Allia...,Peace Agreement between the Great Powers and C...,Boxer Protocol

In [179]:
print(f"WIKI_TREATIES columns: {df_wiki.columns}")
print(f"UNO_TREATIES columns: {df_uno.columns}")
print(f"INSTRUMENTS columns: {df_ins.columns}")
print(f"CONV_PROT_REC columns: {df_conv.columns}")
print(f"RESOLUTIONS_TRIM columns: {df_res.columns}")

WIKI_TREATIES columns: Index(['year', 'name', 'url', 'note', 'summary', 'cleaned_note',
       'cleaned_title'],
      dtype='object')
UNO_TREATIES columns: Index(['title', 'location', 'date', 'chapter'], dtype='object')
INSTRUMENTS columns: Index(['title', 'url', 'adopted_by', 'content', 'pdf_url'], dtype='object')
CONV_PROT_REC columns: Index(['code', 'title', 'year', 'number'], dtype='object')
RESOLUTIONS_TRIM columns: Index(['res_id2', 'part', 'res_id3', 'res_id2_unlet', 'alt_id_dic',
       'session_type', 'session_reg', 'session_sp', 'session_es', 'resn',
       'res_letter', 'date_p', 'date_c', 'filename', 'content', 'location',
       'record', 'draft', 'topic', 'n_inc_cit'],
      dtype='object')

In [180]:
print(f"{'WIKI_TREATIES':=^30}")
print(f"Number of unique cleaned titles: {df_wiki['cleaned_title'].nunique()}\n\
        Length of all titles: {len(df_wiki['cleaned_title'])}")
print(f"Number of unique cleaned alternative names: {df_wiki['cleaned_note'].nunique()}\n\
        Length of all alternative names: {len(df_wiki['cleaned_note'].dropna())}")


print("Non-unique cleaned titles:")
non_unique_titles = df_wiki[df_wiki.duplicated(subset='cleaned_title', keep=False)]
non_unique_titles[['year', 'cleaned_title', 'name']]

========WIKI_TREATIES=========
Number of unique cleaned titles: 345
        Length of all titles: 364
Number of unique cleaned alternative names: 101
        Length of all alternative names: 102
Non-unique cleaned titles:

,year,cleaned_title,name
21,1905,Japan–Korea Treaty,Japan–Korea Treaty of 1905
28,1910,Japan–Korea Treaty,Japan–Korea Treaty of 1910
34,1913,Treaty of London,Treaty of London (1913)
35,1913,Treaty of Bucharest,Treaty of Bucharest (1913)
40,1915,Treaty of London,Treaty of London (1915) (London Pact)
44,1916,Treaty of Bucharest,Treaty of Bucharest (1916)
51,1918,Treaty of Bucharest,Treaty of Bucharest (1918)
64,1920,Treaty of Warsaw,Treaty of Warsaw (1920)
66,1920,Treaty of Rapallo,Treaty of Rapallo (1920)
67,1920,Treaty of Moscow,Treaty of Moscow (1920)
79,1921,Treaty of Berlin,Treaty of Berlin (1921)
83,1921,Treaty of Moscow,Treaty of Moscow (1921)
87,1922,Treaty of Rapallo,Treaty of Rapallo (1922)
93,1924,Treaty of Rome,Treaty of Rome (1924)
97,1926,Treaty of Berlin,Treaty of Berlin (1926)
99,1927,Treaty of Jeddah,Treaty of Jeddah (1927)
116,1937,International Convention for the Regulation of...,International Convention for the Regulation of...
137,1946,International Convention for the Regulation of...,International Convention for the Regulation of...
140,1946,Treaty of London,Treaty of London (1946)
148,1949,Treaty of London,Treaty of London (1949)
169,1957,Treaty of Rome,Treaty of Rome
177,1960,Treaty of Montevideo,1960 Treaty of Montevideo
208,1970,Treaty of Warsaw,Treaty of Warsaw (1970)
227,1973,Agreement on the Transfer of Corpses,Agreement on the Transfer of Corpses
232,1973,Agreement on the Transfer of Corpses,Agreement on the Transfer of Corpses
248,1979,Treaty of Accession,Treaty of Accession 1979
249,1979,Treaty of Montevideo,Treaty of Montevideo
287,1993,Chemical Weapons Convention,Chemical Weapons Convention
308,1997,Chemical Weapons Convention,Chemical Weapons Convention
322,2000,Treaty of Jeddah,Treaty of Jeddah (2000)
335,2003,Treaty of Accession,Treaty of Accession 2003
341,2005,Treaty of Accession,Treaty of Accession 2005
353,2011,Treaty of Accession,Treaty of Accession 2011

In [181]:
print(f"{'UNO_TREATIES':=^50}")
print(f"Number of unique titles: {df_uno['title'].nunique()}\n\
        Length of all titles: {len(df_uno['title'])}")

dupes = (
    df_uno.groupby(["title", "location"])
          .size()
          .reset_index(name="count")
          .query("count > 1")
)
print('Duplicates considering the tile and the loc:')
print(dupes, "\n\n\n")

print(f"{'INSTRUMENTS':=^50}")
print(f"Number of unique titles: {df_ins['title'].nunique()}\n\
        Length of all titles: {len(df_ins['title'])}")

dupes = (
    df_ins.groupby(["title", "adopted_by"])
          .size()
          .reset_index(name="count")
          .query("count > 1")
)

print('Duplicates considering the tile and the date:')
print(dupes, "\n\n\n")

print(f"{'ILO CONVENTIONS AND PROTOCOLS':=^50}")
print(f"Number of unique titles: {df_conv['title'].nunique()}\n\
        Length of all titles: {len(df_conv['title'])}")

dupes = (
    df_conv.groupby(["title", "year"])
          .size()
          .reset_index(name="count")
          .query("count > 1")
)

print('Duplicates considering the tile and the date:')
print(dupes)

===================UNO_TREATIES===================
Number of unique titles: 398
        Length of all titles: 428
Duplicates considering the tile and the loc:
                                                 title  location  count
74   Amendments to the Convention on the Internatio...    London      2
82   Amendments to the title and substantive provis...    London      2
185  Customs Convention on the International Transp...    Geneva      2
194  European Agreement concerning the Work of Crew...    Geneva      2
231                      International Cocoa Agreement    Geneva      5
234                     International Coffee Agreement    London      2
235                     International Coffee Agreement  New York      3
269             International Natural Rubber Agreement    Geneva      2
274                      International Sugar Agreement    Geneva      4
276                      International Sugar Agreement  New York      2



===================INSTRUMENTS====================
Number of unique titles: 100
        Length of all titles: 100
Duplicates considering the tile and the date:
Empty DataFrame
Columns: [title, adopted_by, count]
Index: []



==========ILO CONVENTIONS AND PROTOCOLS===========
Number of unique titles: 407
        Length of all titles: 407
Duplicates considering the tile and the date:
Empty DataFrame
Columns: [title, year, count]
Index: []

In [182]:
'''
De los titulos que si son unicos, podemos usarlos directamente, sin especificar el año.
De los titulos que no son unicos, tenemos que usar el año. Podemos usarlo de las siguientes maneras
- El titulo seguido de "of YEAR"
- El titulo seguido de (YEAR)
- El titulo precedido por YEAR
- El titulo precedido por (YEAR)
Solo el titulo, extraer el fragmento con un padding de 10 caracteres y decidir
'''

'\nDe los titulos que si son unicos, podemos usarlos directamente, sin especificar el año.\nDe los titulos que no son unicos, tenemos que usar el año. Podemos usarlo de las siguientes maneras\n- El titulo seguido de "of YEAR"\n- El titulo seguido de (YEAR)\n- El titulo precedido por YEAR\n- El titulo precedido por (YEAR)\nSolo el titulo, extraer el fragmento con un padding de 10 caracteres y decidir\n'

In [183]:
# Lowercase, otherwise nothing is detected
df_wiki["cleaned_title"] = df_wiki["cleaned_title"].str.lower()

# -------------------------
# Separate unique/non-unique
# -------------------------
unique_titles = df_wiki.drop_duplicates("cleaned_title", keep=False)

non_unique_titles = df_wiki[
    df_wiki.duplicated("cleaned_title", keep=False)
]

# -------------------------
# Collect matches
# -------------------------
MAX_WORD_DIST = 6

records = []

# --- 1. Build map: pattern -> (treaty_id, treaty_title) ---
all_known = []  # (pattern, treaty_id, title)

# Unique titles (no year needed at detection)
for _, t in unique_titles.iterrows():
    all_known.append((
        re.escape(t["cleaned_title"]),
        f'{t["cleaned_title"]};{t["year"]}',
        t["cleaned_title"],
    ))

# Non-unique titles (allow year within MAX_WORD_DIST words)
for _, t in non_unique_titles.iterrows():
    year = str(int(t["year"]))
    title = t["cleaned_title"]

    pat = (
        rf"\b{re.escape(title)}\b(?:\W+\w+){{0,{MAX_WORD_DIST}}}\W+{year}\b"
        rf"|"
        rf"\b{year}\b(?:\W+\w+){{0,{MAX_WORD_DIST}}}\W+{re.escape(title)}\b"
        rf"|"
        rf"\b{re.escape(title)}\s*\({year}\)"
        rf"|"
        rf"\({year}\)\s*{re.escape(title)}"
        rf"|"
        rf"\b{re.escape(title)}\s+of\s+{year}\b"
    )

    all_known.append((pat, f"{title};{year}", title))

# repite para df_1, df_2, df_3 cuando los tengas (con su propio identifier/URL)

# --- 2. Compila UN solo regex con grupos nombrados (o usa un dict índice->id) ---
# Con muchos títulos, mejor usar índice numérico como nombre de grupo
combined_pattern = "|".join(f"(?P<t{i}>{p})" for i, (p, _, _) in enumerate(all_known))
combined_re = re.compile(combined_pattern)
id_lookup = {f"t{i}": (tid, title) for i, (_, tid, title) in enumerate(all_known)}

In [184]:
import os
import pandas as pd
import re
from bisect import bisect_right

# ----------------------------
# SETTINGS
# ----------------------------

df_wiki = pd.read_csv(WIKI_TREATIES)
df_uno = pd.read_csv(UNO_TREATIES)
df_ins = pd.read_csv(INSTRUMENTS)
df_conv = pd.read_csv(CONV_PROT_REC)
df_res = pd.read_csv(RESOLUTIONS_TRIM)
df_uno["year"] = pd.to_datetime(df_uno["date"], format="%d %B %Y").dt.year

df_res = df_res.head(100)


MAX_WORD_DIST = 6


# ----------------------------------------------------
# Function to create regex patterns from a dataframe
# ----------------------------------------------------
def build_known_patterns(
    df,
    title_col,
    identifier_func,
    unique_by=None,
    allow_year_disambiguation=False,
    year_col="year"
):
    """
    Returns:
        list of tuples:
        (regex_pattern, identifier, title)
    """

    patterns = []

    # Default: everything is unique by title
    if unique_by is None:
        unique_rows = df
        non_unique_rows = pd.DataFrame(columns=df.columns)
    else:
        unique_rows = df.drop_duplicates(unique_by, keep=False)
        non_unique_rows = df[df.duplicated(unique_by, keep=False)]


    # -----------------------------
    # Unique titles
    # -----------------------------
    for _, row in unique_rows.iterrows():

        title = row[title_col].lower()

        patterns.append((
            rf"\b{re.escape(title)}\b",
            identifier_func(row),
            title
        ))


    # -----------------------------
    # Non unique titles
    # -----------------------------
    if allow_year_disambiguation:

        for _, row in non_unique_rows.iterrows():

            title = row[title_col].lower()
            year = str(int(row[year_col]))

            pat = (
                rf"\b{re.escape(title)}\b(?:\W+\w+){{0,{MAX_WORD_DIST}}}\W+{year}\b"
                rf"|"
                rf"\b{year}\b(?:\W+\w+){{0,{MAX_WORD_DIST}}}\W+{re.escape(title)}\b"
                rf"|"
                rf"\b{re.escape(title)}\s*\({year}\)"
                rf"|"
                rf"\({year}\)\s*{re.escape(title)}"
                rf"|"
                rf"\b{re.escape(title)}\s+of\s+{year}\b"
            )

            patterns.append((
                pat,
                identifier_func(row),
                title
            ))

    return patterns



# ----------------------------------------------------
# Build all known treaty/instrument patterns
# ----------------------------------------------------

all_known = []


# 1. Wikipedia treaties
all_known.extend(
    build_known_patterns(
        df_wiki,
        title_col="cleaned_title",
        unique_by="cleaned_title",
        allow_year_disambiguation=True,
        identifier_func=lambda r: f'{r["cleaned_title"]};{r["year"]}',
        year_col="year"
    )
)


# 2. UNO Treaties
# Titles are not always unique -> Title + Date
all_known.extend(
    build_known_patterns(
        df_uno,
        title_col="title",
        unique_by=["title", "date"],
        allow_year_disambiguation=True,
        identifier_func=lambda r: f'{r["title"]};{r["date"]}',
        year_col="year"
    )
)


# 3. OHCHR Instruments
# URL is unique
all_known.extend(
    build_known_patterns(
        df_ins,
        title_col="title",
        unique_by="title",
        allow_year_disambiguation=False,
        identifier_func=lambda r: r["url"]
    )
)


# 4. Conventions / Protocols / Recommendations
# Code is unique
all_known.extend(
    build_known_patterns(
        df_conv,
        title_col="title",
        unique_by="code",
        allow_year_disambiguation=False,
        identifier_func=lambda r: r["code"]
    )
)



# ----------------------------------------------------
# Compile ONE regex
# ----------------------------------------------------

combined_pattern = "|".join(
    f"(?P<t{i}>{pattern})"
    for i, (pattern, _, _) in enumerate(all_known)
)

combined_re = re.compile(
    combined_pattern,
    flags=re.IGNORECASE
)


id_lookup = {
    f"t{i}": (identifier, title)
    for i, (_, identifier, title) in enumerate(all_known)
}

In [185]:
records = []
candidates = []

KEYWORDS = [
    "agreement",
    "treaty",
    "convention",
    "protocol",
    "amendment",
    "charter",
    "covenant",
    "pact"
]

AVOID_KEYWORDS = [
    r"treaty series",
    r"treaty\s+series,\s*vol\.",
]

keyword_re = re.compile(
    r"\b(" + "|".join(KEYWORDS) + r")\b",
    re.IGNORECASE
)

avoid_re = re.compile(
    "|".join(AVOID_KEYWORDS),
    re.IGNORECASE
)


WINDOW_CHARS = 100

for _, res in df_res.iterrows():
    content = res["content"]
    res_id2 = res["res_id2"]
    res_part = res["part"]

    known_spans = []  # list of (start, end) already matched

    # --- Known treaty matches ---
    for m in combined_re.finditer(content):
        group_name = m.lastgroup
        tid, title = id_lookup[group_name]

        start = m.start()
        end = m.end()
        window = content[max(0, start - WINDOW_CHARS): min(len(content), end + WINDOW_CHARS)]

        records.append({
            "res_id2": res_id2,
            "res_part": res_part,
            "document": title,
            "id": tid,
            "start": start,
            "end": end,
            "context": window
        })

        known_spans.append((start, end))

    known_spans.sort()
    starts = [s for s, e in known_spans]

    # --- Standalone keyword matches not overlapping known treaties ---
    for km in keyword_re.finditer(content):
        k_start, k_end = km.start(), km.end()

        # Ignore "treaty series, vol." references
        nearby = content[max(0, k_start-30): k_end+30]

        if avoid_re.search(nearby):
            continue

        idx = bisect_right(starts, k_start) - 1
        overlapped = False

        for j in (idx, idx + 1):
            if 0 <= j < len(known_spans):
                s, e = known_spans[j]
                if s <= k_start < e or s < k_end <= e:
                    overlapped = True
                    break

        if not overlapped:
            window = content[max(0, k_start - WINDOW_CHARS): min(len(content), k_end + WINDOW_CHARS)]

            candidates.append({
                "res_id2": res_id2,
                "res_part": res_part,
                "keyword": km.group(),
                "start": k_start,
                "end": k_end,
                "context": window
            })

cites = pd.DataFrame(records).drop_duplicates().reset_index(drop=True)
unknown_candidates = pd.DataFrame(candidates).drop_duplicates().reset_index(drop=True)

In [186]:
pd.set_option("display.max_colwidth", None)
pd.set_option("display.max_rows", None)
unknown_candidates

,res_id2,res_part,keyword,start,end,context
0,997 (es-i),1,agreement,287,296,"ces of israel have penetrated deeply into egyptian terri-tory in violation of the general armistice agreement between egypt and israel of 24 february 1949,"" noting that armed forces of france and the united ki"
1,997 (es-i),1,charter,1720,1727,"o the general assembly, for such further action as they may deem appropriate in accordance with the charter; 6. decides to remain in emergency session pending compliance with the present resolution. 562nd pl"
2,1004 (es-ii),1,treaty,270,276,"nt of human rights and of fundamental freedom in hurigary was specifically guar-anteed by the peace treaty between hungary and the allied and associated powers signed at paris on 10 february 1947, and that"
3,1005 (es-ii),1,treaty,950,956,"iet forces in hungary constitutes a violation of the charter of the united nations and of the peace treaty between hungary and the allied and associated powers, considering that the immediate withdrawal of"
4,1237 (es-iii),1,charter,253,260,"ed “questions considered by the security council at its 838th meeting on 7 august 1958”, noting the charter aim that states should practise tolerance and live together in peace with one another as good neigh"
5,1237 (es-iii),1,pact,415,419,"ether in peace with one another as good neighbours, noting that the arab states have agreed, in the pact of the league of arab states, to strengthen the close relations and numerous ties which link the ar"
6,1237 (es-iii),1,pact,991,995,lcomes the renewed assurances given by the arab states to observe the provision of article 8 of the pact of the league of arab states that each tnember s a‘e shall respect the systems of government establ
7,1237 (es-iii),1,charter,1793,1800,"eneral to make forthwith, in consultation with the governments concerned and in accordance with the charter, and having in mind section i of this resolution, such practical arrangements as would adequately h"
8,1237 (es-iii),1,charter,1952,1959,"uch practical arrangements as would adequately help in upholding the purposes and principles of the charter in relation to lebanon and jordan in the present circumstances, and thereby facilitate the early wi"
9,2252 (es-v),1,treaty,1657,1663,"embly on 26 june 1967;* 5 united nations, treaty series, vol. 75 (1950), no. 972. 6 united nations, treaty sertes, vol. 75 (1950), nos. 970-973. 7 see official records of the general assembly, fifth emer-ge"
10,es-6/2,1,charter,1975,1982,"the char-ter and of the responsibility of the general assembly under the relevant provisions of the charter and of assembly resolution 377 a (v) of 3 november 1950, 1. reaffirms that respect for the sovereig"
11,es-6/2,2,charter,127,134,"ned to assist in bringing about, speedily and in accordance with the purposes and principles of the charter, conditions necessary for the voluntary return of the afghan refugees to their homes; 6. appeals to"
12,es-7/2,2,charter,1290,1297,in order to consider the situation and the adop-tion of effective measures under chapter vii of the charter; 14. decides to adjourn the seventh emergency special session temporarily and to authorize the pres
13,es-7/4,1,convention,2301,2311,"y by force; 3. reaffirms that all the provisions of the hague conventions of 1907 6/ and the geneva convention relative to the protection of civilian persons in time of ‘war, of 12 august 1949, apply to all ter"
14,es-7/4,2,charter,1476,1483,"ael to continue its aggression, occupation and unwillingness to carry out its obligations under the charter and the relevant resolutions of the united nations; 9. urges all governments which have not yet don"
15,es-7/4,2,charter,1864,1871,"raging israel from continuing its aggression, occupation and disregard of its obligations under the charter and the relevant resolutions of the united nations; (c) to act accordingly in all the organs of the"
16,es-7/4,2,charter,2360,2367,it is not a peace~loving member state and that it has carried out neither its obligations under the charter nor its commitment under general assembly resolution 273 (iii) of ll may 1949; 12. calls again upon
17,es-7/4,3,charter,1328,1335,"prehensive, just and lasting solution, conducive to peace, in conformity with the principles of the charter and relevant resolutions and based on the implementation of the recommendations of the committee as"
18,es-7/5,1,charter,1037,1044,"curity council has, so far, failed to take effective and practical measures, in accordance with the charter of the united ‘nations, to ensure implementation of its resolutions 508 (1982) and 509 (1982), refe"
19,es-7/6,1,protocol,1375,1383,of the humanitarian principles and provisions of the geneva conventions of 1949 14/ and additional protocol i thereto 15/ and the obligations arising from the regulations annexed to the hague conventions of
20,es-7/6,2,convention,981,991,"nd 1907 (new york, oxford university press, 1915). ~10-const eated cheggant violation of the geneva convention relative to the vilian persons in time of war, of 12 august 1949, 17/ and also constituted a seriou"
21,es-7/6,3,charter,942,949,eet in order to consider practical ways and means in accordance with the relevant provisions of the charter; 9. requests once again the secretary-general to delegate a high-level commission to investigate an
22,es-7/6,3,charter,2086,2093,"rehensive, just | and lasting solution, conducive to peace in conformity with the principles of the charter and relevant resolutions}. 17/ united nations, treaty series, vol. 75, no. 973, p. 287.-11-12. deci"
23,es-7/7,1,charter,668,675,"nternational peace and security, deeply aware of the responsibility of the united nations under its charter for the maintenance of international peace, gravely concerned that no just solution to the problem"
24,es-8/2,2,charter,241,248,"nd decisions of the general assembly and the security council, thus violating the principles of the charter and defying the authority of the united nations; 5. condemns south africa for its increased oppres-"
25,es-8/2,2,charter,2598,2605,"osing against that country com-prehensive mandatory sanctions as provided for in chapter vii of the charter; \0 {hid., thirty-fifth session, supplement no. 24 (a/35/24), vol. i, annex it. 13. calls upon all"
26,es-9/1,1,charter,1920,1927,"hat it is not a peace-loving member state and that it has not carried out its obligations under the charter, noting further that israel has refused, in violation of afticle 25 of the charter, to accept and c"
27,es-9/1,1,charter,2003,2010,"ations under the charter, noting further that israel has refused, in violation of afticle 25 of the charter, to accept and carry out the numerous relevant decisions of the security council, the latest being"
28,es-9/1,2,charter,1449,1456,"security council which prevented the council from adopting against israel, under chapter vii of the charter, the “appropriate measures” referred to in resolution 497 (1981) unanimously adopted by the council"
29,es-9/1,2,charter,2512,2519,it is not a peace-loving member state and that it has carried out neither its obligations under the charter nor its commitment under general assembly resolution 273 (iii) of 11 may 1949; 12. calls upon all m
30,es-10/2,1,convention,3001,3011,"on of civilian persons in time of war, of 12 august 1949,1 and the regulations annexed to the hague convention iv of 19072 to the occupied palestinian territory, including jerusalem, and all other"
31,es-10/2,2,convention,230,240,"relative to the protection of civilian persons in time of war to respect and ensure respect for the convention in all circumstances, in accordance with article 1 of the convention, conscious of the serious dang"
32,es-10/2,2,convention,299,309,"ect and ensure respect for the convention in all circumstances, in accordance with article 1 of the convention, conscious of the serious dangers arising from persistent violation and grave breaches of the conve"
33,es-10/2,2,convention,404,414,"ntion, conscious of the serious dangers arising from persistent violation and grave breaches of the convention and the responsibilities arising therefrom, convinced that ensuring respect for treaties and other"
34,es-10/2,3,convention,2181,2191,"easures, on a national or regional level, in fulfilment of their obligations under article 1 of the convention, to ensure respect by israel, the occupying power, of the convention; 9. requests the secretary-gen"
35,es-10/2,3,convention,2250,2260,"gations under article 1 of the convention, to ensure respect by israel, the occupying power, of the convention; 9. requests the secretary-general to monitor the situation and to submit a report on the implement"
36,es-10/3,2,convention,1141,1151,"o the protection of civilian persons in time of war convene a conference on measures to enforce the convention in the occupied palestinian territory, including jerusalem, and to ensure its respect, in accordanc"
37,es-10/3,2,charter,1948,1955,"pre-empting permanent status negotiations; 12. stresses the need for actions in accordance with the charter, to continue to ensure respect for international law and relevant united nations resolutions; 13. d"
38,es-10/4,2,convention,560,570,the report of the secretary-general2 of the responses of the high contracting parties to the geneva convention and of the collective responses transmitted through letters from the president of the coordinating
39,es-10/4,2,convention,918,928,"n union, to the note sent by the government of switzerland in its capacity as the depository of the convention, reaffirming the permanent responsibility of the united nations with regard to the question of pale"
40,es-10/4,2,convention,2642,2652,"973. 4 a/es-10/14. /... a/res/es-10/4 page 3 fulfilment of their obligations under article 1 of the convention, to ensure respect by israel, the occupying power, of the convention, as well as its recommendation"
41,es-10/4,2,convention,2711,2721,"gations under article 1 of the convention, to ensure respect by israel, the occupying power, of the convention, as well as its recommendation to member states to actively discourage activities that directly con"
42,es-10/4,3,convention,86,96,"4. reiterates also its recommendation that the high contracting parties to the geneva convention convene a conference on measures to enforce the convention in the occupied palestinian territory, i"
43,es-10/4,3,convention,145,155,"e high contracting parties to the geneva convention convene a conference on measures to enforce the convention in the occupied palestinian territory, including jerusalem, and to ensure its respect in accordance"
44,es-10/4,3,convention,375,385,"1; 5. recommends to the government of switzerland, in its capacity as the depository of the geneva convention, to undertake the necessary steps, including the convening of a meeting of experts in order to foll"
45,es-10/5,1,convention,1088,1098,"to the south of occupied east jerusalem, and its failure to accept the de jure applicability of the convention to the occupied palestinian territory, including jerusalem, and the rest of the arab territories oc"
46,es-10/5,1,convention,2227,2237,"civilian persons in time of war, of 12 august 19491 convene a conference on measures to enforce the convention in the occupied palestinian territory, including jerusalem, and to ensure its respect in accordance"
47,es-10/5,1,convention,2476,2486,"ts recommendation to the government of switzerland, in its capacity as the depositary of the geneva convention, to undertake the necessary preparatory steps, including the convening of a meeting of experts in o"
48,es-10/6,2,convention,97,107,"the occupied palestinian territory, and expressing disappointment that israeli violations of the convention continued unabated in spite of such a measure, taking note also of the meeting of experts of the hi"
49,es-10/6,2,convention,360,370,"r 1998 at the invitation of the government of switzerland, in its capacity as the depositary of the convention, on general problems concerning the convention, in particular in occupied territories, as well as o"
50,es-10/6,2,convention,407,417,"witzerland, in its capacity as the depositary of the convention, on general problems concerning the convention, in particular in occupied territories, as well as of the chairman's report of the proceedings of t"
51,es-10/6,3,convention,2304,2314,"contracting parties to the fourth geneva convention convene a conference on measures to enforce the convention in the occupied palestinian territory, including jerusalem, and to ensure respect thereof in accord"
52,es-10/6,3,convention,2673,2683,"t geneva; 7. invites the government of switzerland, in its capacity as the depositary of the geneva convention, to undertake whatever preparations are necessary prior to the conference; 8. requests the secretar"
53,es-10/7,1,convention,2974,2984,"e conference of high contracting parties to the fourth geneva convention on measures to enforce the convention in the occupied palestinian territory, including jerusalem, at the united nations office at geneva,"
54,es-10/7,3,convention,2286,2296,"tement adopted on 15 july 1999 by the above-mentioned conference of high contracting parties to the convention, with the aim of ensuring respect for the convention in all circumstances in accordance with common"
55,es-10/7,3,convention,2339,2349,"conference of high contracting parties to the convention, with the aim of ensuring respect for the convention in all circumstances in accordance with common article 1 of the four conventions; 11. supports the"
56,es-10/7,3,agreement,2638,2647,"east peace process on its agreed basis, and calls for the speedy conclusion of the final settlement agreement between the two sides; 12. decides to adjourn the tenth emergency special session temporarily and t"
57,es-10/8,2,agreement,242,251,"eration developments in previous discussions between the two sides, and urges them to reach a final agreement on all issues, on the basis of their previous agreements, with the objective of implementing securi"
58,es-10/10,3,convention,868,878,"and international levels to ensure respect by israel, the occupying power, of the provisions of the convention; 6. requests the secretary-general to present a report, drawing upon the available resources and in"
59,es-10/11,1,convention,1390,1400,"of 12 august 1949,2 in the occupied palestinian territory, including jerusalem, and noting that the convention, which takes fully into account imperative military necessity, has to be respected in all circumsta"
60,es-10/14,1,protocol,1652,1660,"ovember 2003, reaffirming the applicability of the fourth geneva convention 1 as well as additional protocol i to the geneva conventions 2 to the occupied palestinian territory, including east jerusalem, ____"
61,es-10/14,2,convention,71,81,"03 64927 a/res/es-10/14 recalling the regulations annexed to the hague convention respecting the laws and customs of war on land of 1907, 3 welcoming the convening of the conference"
62,es-10/14,2,convention,269,279,"e conference of high contracting parties to the fourth geneva convention on measures to enforce the convention in the occupied palestinian territory, including jerusalem, at geneva on 15 july 1999, expressing i"
63,es-10/15,1,charter,600,607,"the united nations, considering that the promotion of respect for the obligations arising from the charter and other instruments and rules of international law is among the basic purposes and principles of"
64,es-10/15,1,convention,1098,1108,"quisition resulting from the threat or use of force, recalling the regulations annexed to the hague convention respecting the laws and customs of war on land of 1907, 1 recalling also the geneva convention rela"
65,es-10/15,1,protocol,1368,1376,"12 august 1949, 2 and relevant provisions of customary law, including those codified in additional protocol i to the geneva conventions, 3 recalling further the international covenant on civil and political"
66,es-10/15,1,covenant,1504,1512,", 3 recalling further the international covenant on civil and political rights, 4 the international covenant on economic, social and cultural rights4 and the convention on the rights of the child, 5 _________"
67,es-10/15,3,convention,1734,1744,"ational law, to ensure compliance by israel with international humanitarian law as embodied in that convention; “e. the united nations, and especially the general assembly and the security council, should consi"
68,es-10/15,4,convention,1502,1512,"calls upon all states parties to the fourth geneva convention 2 to ensure respect by israel for the convention, and invites switzerland, in its capacity as the depositary of the geneva conventions, 11 to conduc"
69,es-10/16,2,agreement,1242,1251,"ian territory for needed treatment, and emphasizes also the importance of the implementation of the agreement of movement and access of november 2005; 9. calls upon the quartet, together with the international"

In [187]:
cites

,res_id2,res_part,document,id,start,end,context
0,1004 (es-ii),1,charter of the united nations,Charter of the United Nations;26 June 1945,467,496,"and that the general principle of these rights and this freedom is «./firmed for all peoples in the charter of the united nations, convinced that recent events in hungary manifest clearly the desire of the hungarian people to exe"
1,1004 (es-ii),1,charter of the united nations,Charter of the United Nations;26 June 1945,2984,3013,ds to bring an end to the foreign intervention in hungary in accordance with the prin-ciples of the charter of the united nations;
2,1005 (es-ii),1,charter of the united nations,Charter of the United Nations;26 June 1945,903,932,"ering that the repression undertaken by the soviet forces in hungary constitutes a violation of the charter of the united nations and of the peace treaty between hungary and the allied and associated powers, considering that the"
3,1007 (es-ii),1,charter of the united nations,Charter of the United Nations;26 June 1945,330,359,"ust effectively through the international eoooperition stipulated in article 1, paragraph 3, of the charter of the united nations, 1. resolves to undertake on a large scale tmmediate aid for the affected territories by furnishing"
4,1474 (es-iv),1,charter of the united nations,Charter of the United Nations;26 June 1945,2509,2538,"of the republic of the congo; (b) all member states, in accordance with ar-ticles 25 and 49 of the charter of the united nations, to accept and carry out the decisions of the security council and to afford mutual assistance in c"
5,2252 (es-v),1,geneva convention relative to the treatment of prisoners of war,https://www.ohchr.org/en/instruments-mechanisms/instruments/geneva-convention-relative-treatment-prisoners-war,649,712,ld be respected even during the vicissitudes of war; (c) considered that all the obligations of the geneva convention relative to the treatment of prisoners of war of 12 august 1949° should be com-plied with by the parties involved in the conflict; (d) called upo
6,es-6/2,1,charter of the united nations,Charter of the United Nations;26 June 1945,870,899,"dependence of any state or in any other manner inconsistent with the purposes and principles of the charter of the united nations, recognizing the urgent need for immediate termina-tion of foreign armed intervention in afghanista"
7,es-6/2,1,charter of the united nations,Charter of the United Nations;26 June 1945,1511,1540,"ternational law concerning friendly rela-tions and co-operation among states in accordance with the charter of the united nations, expressing its deep concern at the dangerous escala-tion of tension, intensification of rivalry an"
8,es-6/2,1,charter of the united nations,Charter of the United Nations;26 June 1945,2186,2215,"ter-ritorial integrity and political independence of every state is a fundamental principle of the charter of the united nations, any violation of which on any pretext whatsoever is contrary to its aims and purposes; 2. strongly"
9,es-7/2,1,charter of the united nations,Charter of the United Nations;26 June 1945,1386,1415,"rehensive, just and lasting peace in the middle east cannot be es-tablished, in accordance with the charter of the united nations and the relevant united nations resolutions, without the withdrawal of israel from all the occupied"
10,es-7/4,1,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,1140,1219,"rch 1980, 476 (1980) of 30 june 1980 and 478 (1980) of 20 august 1980, affirming once more that the geneva convention relative to the protection of civilian persons in time of war, of 12 august 1949, 5/ is applicable to all territories occupied by israel since 1967, including je"
11,es-7/4,2,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,116,195,"el, the occupying power, for its: (a) failure to fulfil its obligations under the provisions of the geneva convention relative to the protection of civilian persons in time of war} (b) disbanding of the elected municipal council of el-bireh; (c) dismissal of the elected mayors o"
12,es-7/4,2,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,2553,2632,"lls again upon israel, the occupying power, to observe and apply scrupulously the provisions of the geneva convention relative to the protection of civilian persons in time of war and the principles of international law governing military occupation in all the occupied palestini"
13,es-7/5,1,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,1188,1267,"ation of its resolutions 508 (1982) and 509 (1982), referring to the humanitarian principles of the geneva convention relative to the protection of civilian persons in time of war, of 12 august 1949, 11/ and to the obligations arising from the regulations annexed to the hague co"
14,es-7/5,2,charter of the united nations,Charter of the United Nations;26 June 1945,650,679,"(1982) and 509 (1982), to meet in order to consider practical ways and means in accordance with the charter of the united nations; 8. calls upon all states and international agencies and organizations to continue to provide the m"
15,es-7/6,1,charter of the united nations,Charter of the United Nations;26 June 1945,704,733,"ecurity council has, so far, failed to take effective and practical measures in accordance with the charter of the united nations to ensure implementation of its resolutions 508 (1982) of 5 june 1962 and 509 (1982) of 6 june 1982"
16,es-7/6,3,charter of the united nations,Charter of the United Nations;26 June 1945,602,631,"l for its non-compliance with resolutious of the security council, in defiance of article 25 of the charter of the united nations; 8. urges once again the security council, in the event of continued failure by israel to comply wi"
17,es-7/9,1,charter of the united nations,Charter of the United Nations;26 June 1945,903,932,"the security council has so far not taken effective and practical measures, in accordance with the charter of the united nations, to ensure implementation of its resolutions 508 (1982) and 509 (1982)., referring to the humanitar"
18,es-7/9,1,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,1054,1133,"tion of its resolutions 508 (1982) and 509 (1982)., referring to the humanitarian principles of the geneva convention relative to the protection of civilian persons in time of war, of 12 august 1949, 21/ and to the obligations arising from the regulations annexed to the hague co"
19,es-7/9,2,charter of the united nations,Charter of the United Nations;26 June 1945,405,434,"he present resolution, to meet in order to consider practical ways and means in accordance with the charter of the united nations; 8. calls upon all states and international agencies and organizations to continue to provide the m"
20,es-8/2,1,charter of the united nations,Charter of the United Nations;26 June 1945,621,650,"solutions proposing comprehensive mandatory sanctions against south africa under chapter vii of the charter of the united nations were vetoed by the three western permanent members of the council on 30 april 1981, noting further"
21,es-8/2,1,charter of the united nations,Charter of the United Nations;26 June 1945,2163,2192,"self-determination, freedom and national in-dependence in a united namibia, in accordance with the charter of the united nations and general assembly resolution 1514 (xv) of 14 december 1960, as well as the subsequent relevant r"
22,es-9/1,1,charter of the united nations,Charter of the United Nations;26 June 1945,1463,1492,"ression”, stressing once again that the acquisition of territory by force is inadmissible under the charter of the united nations, the principles of international law and relevant united nations resolutions, reaffirming once more"
23,es-9/1,1,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,1618,1697,"ational law and relevant united nations resolutions, reaffirming once more the applicability of the geneva convention relative to the protection of civilian persons in time of war, of 12 august 1949,* to the occupied syrian territory, _ noting that israel’s record and actions es"
24,es-9/1,2,charter of the united nations,Charter of the United Nations;26 June 1945,111,140,ed syrian golan heights constitutes an act of aggres-sion under the provisions of article 39 of the charter of the united nations and general assembly resolution 3314 (xxix); 3. declares once more that israel’s decision to impose
25,es-10/2,1,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,2859,2938,"en in relevant united nations resolutions on this matter, reaffirming also the applicability of the geneva convention relative to the protection of civilian persons in time of war, of 12 august 1949,1 and the regulations annexed to the hague convention iv of 19072 to the occupie"
26,es-10/2,2,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,112,191,"ries occupied by israel since 1967, recalling the obligation of the high contracting parties to the geneva convention relative to the protection of civilian persons in time of war to respect and ensure respect for the convention in all circumstances, in accordance with article 1"
27,es-10/2,2,charter of the united nations,Charter of the United Nations;26 June 1945,668,697,"tenance of international peace and security, and determined, in accordance with the preamble to the charter of the united nations, to establish conditions under which justice and respect for the obligations arising from treaties"
28,es-10/2,3,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,1156,1235,"sures and actions in jerusalem; 5. demands also that israel accept the de jure applicability of the geneva convention relative to the protection of civilian persons in time of war, of 12 august 1949,1 to all the territories occupied since 1967, and that it comply with relevant s"
29,es-10/2,3,charter of the united nations,Charter of the United Nations;26 June 1945,1387,1416,"d since 1967, and that it comply with relevant security council resolutions, in accordance with the charter of the united nations; 6. stresses the need to preserve the territorial integrity of all of the occupied palestinian terr"
30,es-10/2,3,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,1992,2071,"ticular settlement activities; 8. recommends to the states that are high contracting parties to the geneva convention relative to the protection of civilian persons in time of war to take measures, on a national or regional level, in fulfilment of their obligations under article"
31,es-10/3,2,charter of the united nations,Charter of the United Nations;26 June 1945,702,731,"hould fulfil in good faith the obligations assumed by them in accordance with the provisions of the charter of the united nations; 9. emphasizes the responsibilities, including personal ones, arising from persistent violations an"
32,es-10/3,2,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,855,934,"onsibilities, including personal ones, arising from persistent violations and grave breaches of the geneva convention relative to the protection of civilian persons in time of war, of 12 august 1949; 2 10. recommends that the high contracting parties to the geneva convention rel"
33,es-10/3,2,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,1013,1092,"ersons in time of war, of 12 august 1949; 2 10. recommends that the high contracting parties to the geneva convention relative to the protection of civilian persons in time of war convene a conference on measures to enforce the convention in the occupied palestinian territory, i"
34,es-10/4,1,charter of the united nations,Charter of the United Nations;26 June 1945,717,746,"f its resolution es-10/2 of 25 april 1997,2 determined to uphold the purposes and principles of the charter of the united nations, international humanitarian law and all other instruments of international law, as well as relevant"
35,es-10/4,1,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,1603,1682,"997/494. 97-77599 /... a/res/es-10/4 page 2 (b) that israel accept the de jure applicability of the geneva convention relative to the protection of civilian persons in time of war, of 12 august 1949,3 to all the territories occupied since 1967, and that it comply with relevant s"
36,es-10/4,1,charter of the united nations,Charter of the United Nations;26 June 1945,1834,1863,"d since 1967, and that it comply with relevant security council resolutions, in accordance with the charter of the united nations; (c) that israel, the occupying power, immediately cease and reverse all actions taken illegally, i"
37,es-10/4,2,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,2361,2440,"ular settlement activities; 3. reiterates its recommendation to the high contracting parties to the geneva convention relative to the protection of civilian persons in time of war,3 to take measures on a national or regional level, in 3 united nations, treaty series, vol. 75, no"
38,es-10/5,1,charter of the united nations,Charter of the United Nations;26 June 1945,536,565,"july 1997 and es-10/4 of 13 november 1997, determined to uphold the purposes and principles of the charter of the united nations, international humanitarian law and all other instruments of international law, as well as relevant"
39,es-10/5,1,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,829,908,"concerned about the persistent violations by israel, the occupying power, of the provisions of the geneva convention relative to the protection of civilian persons in time of war, of 12 august 1949,1 including its settlement construction at jebel abu ghneim to the south of occu"
40,es-10/5,1,geneva convention relative to the protection of civilian persons in time of war,Geneva Convention relative to the Protection of Civilian Persons in Time of War;12 August 1949,2079,2158,"those demands; 3. reiterates once again its recommendation that the high contracting parties to the geneva convention relative to the protection of civilian persons in time of war, of 12 august 19491 convene a conference on measures to enforce the convention in the occupied pale"
41,es-10/6,1,charter of the united nations,Charter of the United Nations;26 June 1945,612,641,"1997 and es–10/5 of 17 march 1998, determined to uphold the purposes and principles embodied in the charter of the united nations, international humanitarian law and all other instruments of international law, as well as relevant"
42,es-10/6,1,fourth geneva convention,Fourth Geneva Convention;1949,2125,2149,"concerned about the persistent violations by israel, the occupying power, of the provisions of the fourth geneva convention relative to the protection of civilian persons in time of war, of 12 august 1949,2 conscious of the"
43,es-10/6,1,fourth geneva convention,Fourth Geneva Convention;1949,2327,2351,"949,2 conscious of the serious dangers arising from persistent violations and grave breaches of the fourth geneva convention and the responsibilities arising therefrom, aware of the upcoming fiftieth anniversary of the four"
44,es-10/6,1,fourth geneva convention,Fourth Geneva Convention;1949,3069,3093,9 to 11 june 1998 and was aimed at examining ways to contribute to the effective application of the fourth geneva convention in
45,es-10/6,3,fourth geneva convention,Fourth Geneva Convention;1949,996,1020,"measures and actions in occupied east jerusalem, the acceptance of the de jure applicability of the fourth geneva convention and compliance with relevant security council resolutions, the cessation and reversal of all action"
46,es-10/6,3,fourth geneva convention,Fourth Geneva Convention;1949,2231,2255,"il resolution 425 (1978); 6. reiterates its recommendation that the high contracting parties to the fourth geneva convention convene a conference on measures to enforce the convention in the occupied palestinian territory, i"
47,es-10/7,1,charter of the united nations,Charter of the United Nations;26 June 1945,2102,2131,"ing any behaviour to the contrary, determined to uphold the purposes and principles embodied in the charter of the united nations, international humanitarian law and all other instruments of 00 71092 a/res/es-10/7 international l"
48,es-10/7,1,fourth geneva convention,Fourth Geneva Convention;1949,2539,2563,"ects, conscious of the serious dangers arising from persistent violations and grave breaches of the fourth geneva convention relative to the protection of civilian persons in time of war, of 12 august 1949, 1 and the respons"
49,es-10/7,1,fourth geneva convention,Fourth Geneva Convention;1949,2922,2946,"onvening, on 15 july 1999, for the first time, of the conference of high contracting parties to the fourth geneva convention on measures to enforce the convention in the occupied palestinian territory, including jerusalem, a"
50,es-10/7,3,fourth geneva convention,Fourth Geneva Convention;1949,970,994,"the occupying power, abide scrupulously by its legal obligations and its responsibilities under the fourth geneva convention relative to the protection of civilian persons in time of war,1 which is applicable to all territor"
51,es-10/7,3,fourth geneva convention,Fourth Geneva Convention;1949,2061,2085,"sibility for the maintenance of international peace and security; 10. invites the depositary of the fourth geneva convention to consult on the development of the humanitarian situation in the field, in accordance with the st"
52,es-10/8,1,fourth geneva convention,Fourth Geneva Convention;1949,1802,1826,"the occupying power, to abide scrupulously by its legal obligations and responsibilities under the fourth geneva convention relative to the protection of civilian persons in time of war of 12 august 1949, 1 1. demands the i"
53,es-10/9,1,fourth geneva convention,Fourth Geneva Convention;1949,1562,1586,"taking note with appreciation of the convening of the conference of high contracting parties to the fourth geneva convention, on 15 july 1999, as recommended by the general assembly in its resolution es-10/6 of 9 february 19"

In [188]:
pd.reset_option("display.max_colwidth")
pd.reset_option("display.max_rows")

"""
1. create a df with the unique titles (cleaned_name column)
2. scan them through the resolution['content]
3. save all in a cites dataframe
4. now the non unique titles (cleaned_name column)
5. scan them non alone through the resolution['content]: they must be accompagned with 'of df['year'], ' (df['year'])', 'df['year'] df['cleaned_name']', '(df['year']) df['cleaned_name']'
6. save everything in cites dataframe
Note: the cites dataframe is resolutions[res_id2], treaty and id, which is composed of the treaty + comma + year
"""

"\n1. create a df with the unique titles (cleaned_name column)\n2. scan them through the resolution['content]\n3. save all in a cites dataframe\n4. now the non unique titles (cleaned_name column)\n5. scan them non alone through the resolution['content]: they must be accompagned with 'of df['year'], ' (df['year'])', 'df['year'] df['cleaned_name']', '(df['year']) df['cleaned_name']'\n6. save everything in cites dataframe\nNote: the cites dataframe is resolutions[res_id2], treaty and id, which is composed of the treaty + comma + year\n"

In [189]:
cites.to_csv("treaty_citations-first-draft.csv", index=False)

In [190]:
"""


Geneva convention. there are many, the first is just geneva convention but the other ones are named by second, third, forth geneva convention. The problem is that the cases where the forth is references, sometimes they dont inlcude the ordinal, so the system detects as the first, but the text next inlcude the date, including 1949
Solution, the geneva convention should also detects a date
Geneva Convention relative to the Protection of Civilian Persons in Time of War, of 12 August 1949 = fourth geneva convention


"""

'\n\n\nGeneva convention. there are many, the first is just geneva convention but the other ones are named by second, third, forth geneva convention. The problem is that the cases where the forth is references, sometimes they dont inlcude the ordinal, so the system detects as the first, but the text next inlcude the date, including 1949\nSolution, the geneva convention should also detects a date\nGeneva Convention relative to the Protection of Civilian Persons in Time of War, of 12 August 1949 = fourth geneva convention\n\n\n'

In [191]:
# group to see the most cited treaties
cites = (
    cites.groupby('id')
         .agg(count=('res_id2', 'count'))
         .reset_index()
)

In [192]:
cites.sort_values(by='count', ascending=False, inplace=True)
print(cites.head(10))

                                                  id  count
0         Charter of the United Nations;26 June 1945     33
2                      Fourth Geneva Convention;1949     26
3  Geneva Convention relative to the Protection o...     22
1  Convention on the Rights of the Child;20 Novem...      1
4  International Covenant on Civil and Political ...      1
5  Rome Statute of the International Criminal Cou...      1
6                        United Nations Charter;1945      1
7  https://www.ohchr.org/en/instruments-mechanism...      1